describe('Form Inputs', () => {
    it('can navigate to the site', () => {
        cy.visit('http://localhost:3000')
        cy.url().should('include', 'localhost')    
    })
    it('button is disabled', () => {
        cy.get('button')
        .should('be.disabled')
    })
    it('can type a first name', () => {
        cy.get('input[name="first_name"]')
        .type('Jane')
        .should('have.value', 'Jane')
    })
    it('can type a last name', () => {
        cy.get('input[name="last_name"]')
        .type('Doe')
        .should('have.value', 'Doe')
    })
    it('can type a email', () => {
        cy.get('input[name="email"]')
        .type('janedoe@email.com')
        .should('have.value', 'janedoe@email.com')
    })
    it('can type a password', () => {
        cy.get('input[name="password"]')
        .type('password')
        .should('have.value', 'password')
    })
    it('check terms and conidtions box', () => {
        cy.get('input[name="terms"]')
        .check()
        .should('have.value', 'true')
    })
    it('submit button', () => {
        cy.get('button').should('not.be.disabled')
    })
})
describe('Form Validations', () => {
it('validates first_name correctly', () => {
    cy.visit('http://localhost:3000')
    cy.contains('first Name is required').should('not.exist')
    cy.get('input[name="first_name"]').type(' ')
    cy.contains('First Name is Required')
})
it('validates last_name correctly', () => {
    cy.visit('http://localhost:3000')
    cy.contains('Last Name is required').should('not.exist')
    cy.get('input[name="last_name"]').type(' ')
    cy.contains('Last Name is Required')
})
it('validates email correctly', () => {
    cy.visit('http://localhost:3000')
    cy.contains('the email must be a valid email address').should('not.exist')
    cy.get('input[name="email"]').type('abc')
    cy.contains('the email must be a valid email address')
    cy.get('input[name="email"]').type('@email')
    cy.contains('the email must be a valid email address')
    cy.get('input[name="email"]').type('.com')
    cy.contains('the email must be a valid email address').should('not.exist')
})
it('validates password correctly', () => {
    cy.visit('http://localhost:3000')
    cy.contains('The password must be at least seven characters long').should('not.exist')
    cy.get('input[name="password"]').type('a')
    cy.contains('The password must be at least seven characters long')
    cy.get('input[name="password"]').type('b')
    cy.contains('The password must be at least seven characters long')
    cy.get('input[name="password"]').type('c')
    cy.contains('The password must be at least seven characters long')
    cy.get('input[name="password"]').type('d')
    cy.contains('The password must be at least seven characters long')
    cy.get('input[name="password"]').type('e')
    cy.contains('The password must be at least seven characters long')
    cy.get('input[name="password"]').type('f')
    cy.contains('The password must be at least seven characters long')
    cy.get('input[name="password"]').type('g')
    cy.contains('The password must be at least seven characters long').should('not.exist')
})
})
describe('Submitting Form', () => {
    it('can submit a new user', () => {
        cy.visit('http://localhost:3000')
        cy.get('input[name="first_name"]').type('John')
        cy.get('input[name="last_name"]').type('Doe')
        cy.get('input[name="password"]').type('password')
        cy.get('input[name="email"]').type('johndoe@email.com')
        cy.get('input[name="terms"]').check()
        cy.get('button').click()
        cy.wait(1000)
        cy.get('.userBox h2').contains('John').should('exist')
    })

})